insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark)values (1,1,'正常','0','normal_status','primary','stitch',sysdate(),'',sysdate(),'0','系统默认状态:正常');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (2,2,'停用','1','normal_status','warning','stitch',sysdate(),'',sysdate(),'0','系统默认状态:停用');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (3,1,'内置','1','normal_system','primary','stitch',sysdate(),'',sysdate(),'0','字典是否内置:内置');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (4,2,'非内置','0','normal_system','warning','stitch',sysdate(),'',sysdate(),'0','字典是否内置:非内置');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (5,1,'正常','0','menu_status','primary','stitch',sysdate(),'',sysdate(),'0','菜单状态:正常');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (6,2,'停用','1','menu_status','warning','stitch',sysdate(),'',sysdate(),'0','菜单状态:停用');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (7,1,'男','0','user_gender','primary','stitch',sysdate(),'',sysdate(),'0','用户性别:男');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (8,2,'女','1','user_gender','warning','stitch',sysdate(),'',sysdate(),'0','用户性别:女');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (9,3,'未知','2','user_gender','danger','stitch',sysdate(),'',sysdate(),'0','用户性别:未知');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (10,1,'正常','0','user_status','primary','stitch',sysdate(),'',sysdate(),'0','用户状态:正常');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (11,2,'停用','1','user_status','warning','stitch',sysdate(),'',sysdate(),'0','用户状态:停用');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (12,1,'正常','0','role_status','primary','stitch',sysdate(),'',sysdate(),'0','角色状态:正常');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (13,2,'停用','1','role_status','warning','stitch',sysdate(),'',sysdate(),'0','角色状态:停用');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (14,1,'正常','0','post_status','primary','stitch',sysdate(),'',sysdate(),'0','岗位状态:正常');
insert into sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, create_user, create_time, update_user, update_time, is_delete, remark) values (15,2,'停用','1','post_status','warning','stitch',sysdate(),'',sysdate(),'0','岗位状态:停用');


